name: release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  release:
    permissions:
      contents: write
    name: ubuntu / release
    runs-on: ubuntu-latest
    steps:
      - name: "checkout code"
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install stable
        uses: dtolnay/rust-toolchain@stable
      - name: build application
        run: VERSION=${{ github.ref_name }} RUSTFLAGS='-C target-feature=+crt-static' cargo build --verbose --release --target x86_64-unknown-linux-gnu
      - name: rename binary
        run: mv target/x86_64-unknown-linux-gnu/release/fzf-dclist fzf-dclist-linux-amd64-${{ github.ref_name }}
      - name: create release with binaries
        uses: softprops/action-gh-release@v1
        with:
          files: fzf-dclist-linux-amd64-${{ github.ref_name }}
