#! /usr/bin/env bash

set -o pipefail
set -o errexit
set -o nounset

expected=$(cat <<EOF
web:80            [running]  http://localhost:8080
documentation:80  [exited]   http://localhost:8081
EOF
)
actual=$(</dev/stdin);

diff <(echo "${expected}") <(echo "${actual}")
